{% set name = "kymotools" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kymotools-{{ version }}.tar.gz
  sha256: c5734786be2dad8f5bf4e54a5326b9f294a9b8895ba8d07802131f19b139fe5e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - pip
  run:
    - python >=3.8
    - matplotlib-base >=3.0.0
    - scipy >=1.0.0
    - tifffile >=2021.1.8
    - tqdm >=4.1.0

test:
  imports:
    - kymotools
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Scripts for kymograph processing
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sjcross
