{% set name = "kymotools" %}
{% set version = "0.4.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kymotools-{{ version }}.tar.gz
  sha256: a7dc29e7fa64aedf1669ecfb6e9bd9b7696c96da4fa060b21f532dff923c1cf8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - pip
  run:
    - python >=3.8
    - matplotlib-base >=3.0.0
    - scipy >=1.0.0
    - tifffile >=2021.1.8
    - tqdm >=4.1.0

test:
  imports:
    - kymotools
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Scripts for kymograph processing
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sjcross
